cards = [
    criaCartao('Naruto', 'Qual é o sonho de Naruto Uzumaki?', 'Tornar-se Hokage.'),
    criaCartao('One Piece', 'O que Luffy busca durante sua jornada?', 'O tesouro One Piece.'),
    criaCartao('Dragon Ball', 'Qual é a transformação mais famosa de Goku?', 'Super Saiyajin.'),
    criaCartao('Death Note', 'Qual é o nome do Shinigami que acompanha Light Yagami?', 'Ryuk.'),
    criaCartao('Attack on Titan', 'Qual é a habilidade especial de Eren Yeager?', 'Transformar-se em um Titã.'),
    criaCartao('Fullmetal Alchemist', 'Qual é o nome do irmão mais novo de Edward Elric?', 'Alphonse Elric.'),
    criaCartao('My Hero Academia', 'Qual é o nome do protagonista de My Hero Academia?', 'Izuku Midoriya (Deku).'),
    criaCartao('Demon Slayer', 'Qual é o objetivo de Tanjiro Kamado?', 'Curar sua irmã Nezuko e derrotar Muzan Kibutsuji.'),
    criaCartao('Sword Art Online', 'Qual é o nome do primeiro jogo em que Kirito fica preso?', 'Sword Art Online.'),
    criaCartao('Hunter x Hunter', 'Qual é o nome do melhor amigo de Gon?', 'Killua Zoldyck.'),
    criaCartao('Bleach', 'Qual é o nome da espada de Ichigo?', 'Zangetsu.'),
    criaCartao('Tokyo Ghoul', 'Quem é o protagonista de Tokyo Ghoul?', 'Ken Kaneki.'),
    criaCartao('Fairy Tail', 'Qual é o nome do Exceed que acompanha Natsu?', 'Happy.'),
    criaCartao('Pokémon', 'Qual é o Pokémon inicial de Ash?', 'Pikachu.'),
    criaCartao('Black Clover', 'Qual é o sonho de Asta?', 'Tornar-se o Rei Mago.'),
    criaCartao('Code Geass', 'Qual é o poder de Lelouch?', 'Geass, que permite controlar a mente de outros.'),
    criaCartao('Re:Zero', 'Qual é a habilidade especial de Subaru?', 'Retornar pela morte.'),
    criaCartao('Your Lie in April', 'Qual é o instrumento tocado por Kousei Arima?', 'Piano.'),
    criaCartao('Cowboy Bebop', 'Qual é o nome do protagonista?', 'Spike Spiegel.'),
    criaCartao('Neon Genesis Evangelion', 'Quem pilota o EVA-01?', 'Shinji Ikari.'),
    criaCartao('Haikyuu!!', 'Qual esporte é o tema principal de Haikyuu!!?', 'Voleibol.'),
    criaCartao('Steins;Gate', 'Qual é o dispositivo usado para enviar mensagens ao passado?', 'Microondas Telefônico.'),
    criaCartao('Jujutsu Kaisen', 'Qual é o nome do protagonista de Jujutsu Kaisen?', 'Yuji Itadori.'),
    criaCartao('Clannad', 'Qual é o tema principal de Clannad?', 'Família e laços emocionais.'),
    criaCartao('Toradora!', 'Quem são os dois protagonistas de Toradora!?', 'Ryuuji Takasu e Taiga Aisaka.'),
    criaCartao('Akame ga Kill!', 'Qual é o objetivo do Night Raid?', 'Derrubar o Império corrupto.'),
    criaCartao('Kuroko no Basket', 'Qual é o esporte principal de Kuroko no Basket?', 'Basquete.'),
    criaCartao('The Promised Neverland', 'Qual é o objetivo das crianças de Grace Field?', 'Escapar do orfanato.'),
    criaCartao('Erased', 'Qual é a habilidade de Satoru Fujinuma?', 'Voltar no tempo para evitar tragédias.'),
    criaCartao('Violet Evergarden', 'O que Violet deseja entender?', 'O significado da frase "Eu te amo".'),
    criaCartao('Noragami', 'Quem é o deus principal em Noragami?', 'Yato.'),
    criaCartao('Parasyte', 'Qual é o nome do parasita que vive no corpo de Shinichi?', 'Migi.'),
    criaCartao('Mob Psycho 100', 'Qual é o poder especial de Mob?', 'Poderes psíquicos.'),
    criaCartao('Gintama', 'Qual é o trabalho principal de Gintoki?', 'Faz-tudo (Yorozuya).'),
    criaCartao('Made in Abyss', 'Qual é o objetivo de Riko na história?', 'Encontrar sua mãe no Abismo.'),
    criaCartao('Berserk', 'Quem é o protagonista de Berserk?', 'Guts.'),
    criaCartao('No Game No Life', 'Qual é o nome da dupla de protagonistas?', 'Sora e Shiro.'),
    criaCartao('Shingeki no Bahamut', 'Qual é a relação de Favaro e Kaisar?', 'Rivais e aliados.'),
    criaCartao('Samurai Champloo', 'Qual é a missão principal de Fuu?', 'Encontrar o "samurai que cheira a girassóis".'),
    criaCartao('Dr. Stone', 'Qual é o objetivo de Senku?', 'Restaurar a civilização usando ciência.'),
    criaCartao('Great Teacher Onizuka', 'Qual é o sonho de Onizuka?', 'Tornar-se o melhor professor.'),
    criaCartao('Trigun', 'Qual é o apelido do protagonista Vash?', 'O Tufão Humanoide.'),
    criaCartao('Psycho-Pass', 'Qual é o nome do sistema que mede a psicologia das pessoas?', 'Sistema Sibyl.'),
    criaCartao('Elfen Lied', 'Qual é o nome da protagonista diclonius?', 'Lucy/Nyu.'),
    criaCartao('Hellsing', 'Quem é o vampiro protagonista?', 'Alucard.'),
    criaCartao('K-On!', 'Qual é o nome da banda formada pelas protagonistas?', 'Ho-kago Tea Time.'),
    criaCartao('Spirited Away', 'Qual é o nome da protagonista de A Viagem de Chihiro?', 'Chihiro Ogino.'),
    criaCartao('Howl’s Moving Castle', 'Quem é o mago principal da história?', 'Howl.'),
    criaCartao('Princess Mononoke', 'Qual é o nome da jovem que vive com lobos?', 'San.'),
    criaCartao('Akira', 'Qual é o nome do protagonista que ganha poderes psíquicos?', 'Tetsuo Shima.')
]



